### ISSUE TITLE
English translation?

### ISSUE THREAD

**Issue by rotatingJazz** [raphaelgoetter/KNACSS#117]
Are there any plans to get the documentation on English as well? I was using v.3 and I'd be interested in switching to v.4 but the language barrier is a problem.

**Comment by raphaelgoetter** [comment]
Hello, no it is not planned at the moment, I'm sorry

However, all the files and comments in files are in english.

**Comment by datiswous** [comment]
Hello. The old website and documentation for version 3 was in English. Do you have a copy of that available? Also there was a Cheatsheet which now points to a French file, before it was in English.

I was kind of relying on the documentation to learn how this framwork works. I find it strange that everything is removed without warning and explenation.

**Comment by raphaelgoetter** [comment]
The old documentation can be found here : http://knacss.com/archive/doc.html

You can find the english V3 Cheatsheet here : http://knacss.com/KNACSS-cheatsheet-old.pdf

About the French language choice : a [long discussion](https://github.com/raphaelgoetter/KNACSS/issues/99#issuecomment-65944006) occured about the language to use in KNACSS and we decided to keep french only.

**Comment by datiswous** [comment]
Thanks!

Btw. The with on that page is 18em, so it overides the content. Changing to 10em makes it better.

It seams Google translate French -> English works ok. I might just use that in the future. It would still be nice if the project has a possibility to translate the doc-pages. So that individual users can do that if needed.
